#!/bin/sh

. /usr/lib/live/config.sh

## Set koder user password (runs after 0030-user-setup)

Init ()
{
	if component_was_executed "koder-password"
	then
		exit 0
	fi

	echo -n " koder-password"
}

Config ()
{
	LIVE_USERNAME="${LIVE_USERNAME:-koder}"
	echo "${LIVE_USERNAME}:koder@123" | chpasswd

	# Creating state file
	touch /var/lib/live/config/koder-password
}

Init
Config
